improvement: show version number in main GUI improvement: get changelog into github releases task: bump version number to 0.3.0

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,10 +20,20 @@ defaults: &defaults
     - run:
         name: Version checks
         command: |
-            grep -q $VERSION notebooker/_version.py || (echo "ERROR: Version number not found in notebooker/_version.py: $VERSION"; exit 1)
+            grep -q $VERSION notebooker/version.py || (echo "ERROR: Version number not found in notebooker/_version.py: $VERSION"; exit 1)
             grep -q $VERSION CHANGELOG.md || (echo "ERROR: Version number not found in CHANGES.md: $VERSION"; exit 1)
             grep -q $VERSION docs/conf.py || (echo "ERROR: Version number not found in docs/source/conf.py: $VERSION"; exit 1)
             grep -q $VERSION notebooker/web/static/package.json || (echo "ERROR: Version number not found in package.json: $VERSION"; exit 1)
+    - run:
+        name: Output useful stuff
+        command: |
+          echo $VERSION > "$CIRCLE_ARTIFACTS/version.txt"
+          # Find the lines of the changelog between releases, escape double quotes, delete empty lines
+          sed -n '{ /------/= }' CHANGELOG.md \
+              | head -n 2 \
+              | xargs -n 2 bash -c 'sed -n "s/\"/\\\\\"/g;`expr $0 + 1`,`expr $1 - 2`p" CHANGELOG.md' \
+              | sed '/^$/d' \
+              > "$CIRCLE_ARTIFACTS/changes.md"
     - run:
         name: Install MongoDB
         command: |
@@ -139,10 +149,6 @@ defaults: &defaults
     - run:
         name: Upload to PyPI
         command: |
-          echo $VERSION > "$CIRCLE_ARTIFACTS/version.txt"
-    - run:
-        name: Upload to PyPI
-        command: |
           set -e
           if [ "$CIRCLE_BRANCH" = "master" ]; then
             . ci/bin/activate
@@ -162,6 +168,7 @@ defaults: &defaults
         root: /tmp/circleci-artifacts
         paths:
           - ./*/version.txt
+          - ./*/changes.md
           - ./*/dist/*
 version: 2
 jobs:
@@ -170,7 +177,7 @@ jobs:
       PYTHON_VERSION: "3_6"
       CIRCLE_ARTIFACTS: /tmp/circleci-artifacts/3_6
       CIRCLE_TEST_REPORTS: /tmp/circleci-test-results/3_6
-      VERSION: 0.2.1
+      VERSION: 0.3.0
       PANDOC_RELEASES_URL: https://github.com/jgm/pandoc/releases
       YARN_STATIC_DIR: notebooker/web/static/
       IMAGE_NAME: mangroup/notebooker
@@ -182,7 +189,7 @@ jobs:
     environment:
       CIRCLE_ARTIFACTS: /tmp/circleci-artifacts/3_7
       CIRCLE_TEST_REPORTS: /tmp/circleci-test-results/3_7
-      VERSION: 0.2.1
+      VERSION: 0.3.0
       PANDOC_RELEASES_URL: https://github.com/jgm/pandoc/releases
       YARN_STATIC_DIR: notebooker/web/static/
       IMAGE_NAME: mangroup/notebooker
@@ -200,7 +207,15 @@ jobs:
           name: "Publish release on GitHub"
           command: |
             VERSION=$(cat /tmp/circleci-artifacts/3_6/version.txt)
-            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -soft ${VERSION} /tmp/circleci-artifacts/3_6/dist
+            CHANGES=$(cat /tmp/circleci-artifacts/3_6/changes.md)
+            ghr -t ${GITHUB_TOKEN} \
+                -u ${CIRCLE_PROJECT_USERNAME} \
+                -r ${CIRCLE_PROJECT_REPONAME} \
+                -c ${CIRCLE_SHA1} \
+                -n ${VERSION} \
+                -b "${CHANGES}" \
+                -soft \
+                ${VERSION} /tmp/circleci-artifacts/3_6/dist
 workflows:
   version: 2
   build_all:
