Adding some more colour to CHANGELOG and attempting fix of MongoDB in circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,7 +5,7 @@ defaults: &defaults
       CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
       CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
       # CODECOV_TOKEN: b0d35139-0a75-427a-907b-2c78a762f8f0
-      VERSION: 0.0.2
+      VERSION: 0.1.0
       PANDOC_RELEASES_URL: https://github.com/jgm/pandoc/releases
       YARN_STATIC_DIR: notebooker/web/static/
       IMAGE_NAME: mangroup/notebooker
@@ -26,26 +26,37 @@ defaults: &defaults
         keys:
           - yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
     - run:
-        name: Install JS Dependencies
+        name: Version checks
         command: |
-          pushd $YARN_STATIC_DIR
-          yarn install --frozen-lockfile
-    - save_cache:
-        name: Save Yarn Package Cache
-        key: yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
-        paths:
-          - ~/.cache/yarn
+            grep -q $VERSION notebooker/_version.py || (echo "ERROR: Version number not found in notebooker/_version.py: $VERSION"; exit 1)
+            grep -q $VERSION CHANGELOG.md || (echo "ERROR: Version number not found in CHANGES.md: $VERSION"; exit 1)
+            grep -q $VERSION docs/conf.py || (echo "ERROR: Version number not found in docs/source/conf.py: $VERSION"; exit 1)
+            grep -q $VERSION notebooker/web/static/package.json || (echo "ERROR: Version number not found in package.json: $VERSION"; exit 1)
     - run:
         name: Install MongoDB
         command: |
             # run "cat /etc/os-release" to view information about the OS
-            # good article on how to install mongo, https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
+            # good article on how to install mongo, https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
+
+            cat /etc/os-release
+            set -x
             wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
             sudo apt-get install gnupg
             wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
-            echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
+            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
             sudo apt-get update
-            sudo apt-get install -y mongodb-org
+            sudo ln -s /bin/true /bin/systemctl
+            sudo apt-get install -y mongodb-org=4.2.11 mongodb-org-server=4.2.11 mongodb-org-shell=4.2.11 mongodb-org-mongos=4.2.11 mongodb-org-tools=4.2.11
+    - run:
+        name: Install JS Dependencies
+        command: |
+            pushd $YARN_STATIC_DIR
+            yarn install --frozen-lockfile
+    - save_cache:
+        name: Save Yarn Package Cache
+        key: yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
+        paths:
+            - ~/.cache/yarn
     - run:
         name: Lint & Format JS Code
         command: |
@@ -88,12 +99,15 @@ defaults: &defaults
     - run:
        name: Run all tests
        command: |
+         set -x
          . ci/bin/activate
+         ls -la /bin | grep mongo
+         which mongod
          pip install -e .[prometheus,test]
          python -m ipykernel install --user --name=notebooker_kernel
          pip install -r ./notebooker/notebook_templates_example/notebook_requirements.txt
          mkdir test-results
-         pytest --junitxml=test-results/junit.xml
+         py.test -svvvvv --junitxml=test-results/junit.xml
          # bash <(curl -s https://codecov.io/bash) -c -F python
     - run:
         name: Build Sphinx Documentation
@@ -111,10 +125,6 @@ defaults: &defaults
           . ci/bin/activate
           pip install docutils
           pip install Pygments
-          grep -q $VERSION notebooker/_version.py || (echo "ERROR: Version number not found in notebooker/_version.py: $VERSION"; exit 1)
-          grep -q $VERSION CHANGELOG.md || (echo "ERROR: Version number not found in CHANGES.md: $VERSION"; exit 1)
-          grep -q $VERSION docs/conf.py || (echo "ERROR: Version number not found in docs/source/conf.py: $VERSION"; exit 1)
-          grep -q $VERSION notebooker/web/static/package.json || (echo "ERROR: Version number not found in package.json: $VERSION"; exit 1)
           python setup.py --long-description > ../README.rst
           cat ../README.rst | rst2html.py 1> ../README.html 2> ../log
           cp ../README.rst /tmp/circleci-artifacts
@@ -150,15 +160,9 @@ jobs:
     docker:
     - image: cimg/python:3.7-node
     <<: *defaults
-  build_3_8:
-    working_directory: ~/notebooker_3_8
-    docker:
-    - image: cimg/python:3.8-node
-    <<: *defaults
 workflows:
   version: 2
   build_all:
     jobs:
       - build_3_6
       - build_3_7
-      - build_3_8
