Upgrade CircleCI config to version 2.1.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,194 +1,196 @@
 defaults: &defaults
     parallelism: 1
     shell: /bin/bash --login
-steps: &default_steps
-  - checkout
-  - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
-  # Restore the dependency cache
-  - restore_cache:
-      keys:
-      # This branch if available
-      - v1-dep-{{ .Branch }}-
-      # Default branch if not
-      - v1-dep-master-
-      # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
-      - v1-dep-
-  - restore_cache:
-      name: Restore Yarn Package Cache
-      keys:
-        - yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
-  - run:
-      name: Version checks
-      command: |
-          grep -q $VERSION notebooker/version.py || (echo "ERROR: Version number not found in notebooker/_version.py: $VERSION"; exit 1)
-          grep -q $VERSION CHANGELOG.md || (echo "ERROR: Version number not found in CHANGES.md: $VERSION"; exit 1)
-          grep -q $VERSION docs/conf.py || (echo "ERROR: Version number not found in docs/source/conf.py: $VERSION"; exit 1)
-          grep -q $VERSION notebooker/web/static/package.json || (echo "ERROR: Version number not found in package.json: $VERSION"; exit 1)
-  - run:
-      name: Output useful stuff
-      command: |
-        echo $VERSION > "$CIRCLE_ARTIFACTS/version.txt"
-        # Find the lines of the changelog between releases, escape double quotes, delete empty lines
-        sed -n '{ /------/= }' CHANGELOG.md \
-            | head -n 2 \
-            | xargs -n 2 bash -c 'sed -n "s/\"/\\\\\"/g;`expr $0 + 1`,`expr $1 - 2`p" CHANGELOG.md' \
-            | sed '/^$/d' \
-            > "$CIRCLE_ARTIFACTS/changes.md"
-  - run:
-      name: Install MongoDB
-      command: |
-          # run "cat /etc/os-release" to view information about the OS
-          # good article on how to install mongo, https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
-
-          cat /etc/os-release
-          set -x
-          # ------ (2022-10-28) install libssl1.1 since mongo doesn't support Ubuntu 22.04 which has libssl v3 
-          echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
-          sudo apt-get update
-          sudo apt-get install libssl1.1
-          # -------
-          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
-          sudo apt-get install gnupg
-          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
-          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
-          sudo apt-get update
-          sudo ln -Tf /bin/true /usr/bin/systemctl
-          sudo apt-get install -y mongodb-org=4.2.11 mongodb-org-server=4.2.11 mongodb-org-shell=4.2.11 mongodb-org-mongos=4.2.11 mongodb-org-tools=4.2.11
-          sudo rm /usr/bin/systemctl
-  - run:
-      name: Install JS Dependencies
-      command: |
+commands:
+  default_build:
+    steps:
+    - checkout
+    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
+    # Restore the dependency cache
+    - restore_cache:
+        keys:
+        # This branch if available
+        - v1-dep-{{ .Branch }}-
+        # Default branch if not
+        - v1-dep-master-
+        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
+        - v1-dep-
+    - restore_cache:
+        name: Restore Yarn Package Cache
+        keys:
+          - yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
+    - run:
+        name: Version checks
+        command: |
+            grep -q $VERSION notebooker/version.py || (echo "ERROR: Version number not found in notebooker/_version.py: $VERSION"; exit 1)
+            grep -q $VERSION CHANGELOG.md || (echo "ERROR: Version number not found in CHANGES.md: $VERSION"; exit 1)
+            grep -q $VERSION docs/conf.py || (echo "ERROR: Version number not found in docs/source/conf.py: $VERSION"; exit 1)
+            grep -q $VERSION notebooker/web/static/package.json || (echo "ERROR: Version number not found in package.json: $VERSION"; exit 1)
+    - run:
+        name: Output useful stuff
+        command: |
+          echo $VERSION > "$CIRCLE_ARTIFACTS/version.txt"
+          # Find the lines of the changelog between releases, escape double quotes, delete empty lines
+          sed -n '{ /------/= }' CHANGELOG.md \
+              | head -n 2 \
+              | xargs -n 2 bash -c 'sed -n "s/\"/\\\\\"/g;`expr $0 + 1`,`expr $1 - 2`p" CHANGELOG.md' \
+              | sed '/^$/d' \
+              > "$CIRCLE_ARTIFACTS/changes.md"
+    - run:
+        name: Install MongoDB
+        command: |
+            # run "cat /etc/os-release" to view information about the OS
+            # good article on how to install mongo, https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
+  
+            cat /etc/os-release
+            set -x
+            # ------ (2022-10-28) install libssl1.1 since mongo doesn't support Ubuntu 22.04 which has libssl v3 
+            echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
+            sudo apt-get update
+            sudo apt-get install libssl1.1
+            # -------
+            wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
+            sudo apt-get install gnupg
+            wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
+            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
+            sudo apt-get update
+            sudo ln -Tf /bin/true /usr/bin/systemctl
+            sudo apt-get install -y mongodb-org=4.2.11 mongodb-org-server=4.2.11 mongodb-org-shell=4.2.11 mongodb-org-mongos=4.2.11 mongodb-org-tools=4.2.11
+            sudo rm /usr/bin/systemctl
+    - run:
+        name: Install JS Dependencies
+        command: |
+            pushd $YARN_STATIC_DIR
+            yarn install --frozen-lockfile $EXTRA_YARN_INSTALL_ARGS
+    - save_cache:
+        name: Save Yarn Package Cache
+        key: yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
+        paths:
+            - ~/.cache/yarn
+    - run:
+        name: Lint & Format JS Code
+        command: |
           pushd $YARN_STATIC_DIR
-          yarn install --frozen-lockfile $EXTRA_YARN_INSTALL_ARGS
-  - save_cache:
-      name: Save Yarn Package Cache
-      key: yarn-packages-{{ checksum "notebooker/web/static/yarn.lock" }}
-      paths:
-          - ~/.cache/yarn
-  - run:
-      name: Lint & Format JS Code
-      command: |
-        pushd $YARN_STATIC_DIR
-        yarn run lint
-  - run:
-      name: Check for JS Formatting Diffs
-      command: |
-        git diff --name-status
-        git diff-files --quiet || (echo 'The files above have not been formatted!' && (exit 1))
-  - run:
-      name: Browserify
-      command: |
-           pushd $YARN_STATIC_DIR
-           yarn run bundle
-  - run:
-      name: JS tests
-      command: |
-           pushd $YARN_STATIC_DIR
-           yarn test
-  - run:
-     name: Create and activate virtualenv
-     command: |
-       virtualenv ci
-       . ci/bin/activate
-       pip install six lxml flake8 tox pytest black .[test]
-       pip install --editable .
-  # Save dependency cache
-  - save_cache:
-      key: v1-dep-{{ .Branch }}-{{ epoch }}
-      paths:
-      - ~/ci
-  - run:
-      name: Run Flake8
-      command: |
-        . ci/bin/activate
-        flake8 notebooker tests
-  - run:
-      name: Run black
-      command: |
-        . ci/bin/activate
-        black --check -l 120 notebooker tests
-        if [ $? -eq 0 ]
-        then
-          echo "Black worked fine."
-        else
-          echo "Black found differences!"; exit $?
-        fi
-  # Test
-  - run:
-     name: Run all tests
-     command: |
-       set -x
-       . ci/bin/activate
-       ls -la /bin | grep mongo
-       which mongod
-       pip install -e .[prometheus,test]
-       python -m ipykernel install --user --name=notebooker_kernel
-       pip install -r ./notebooker/notebook_templates_example/notebook_requirements.txt
-       mkdir test-results
-       py.test -svvvvv --junitxml=test-results/junit.xml
-       # bash <(curl -s https://codecov.io/bash) -c -F python
-  - run:
-      name: Build Sphinx Documentation
-      command: |
-        set -e
-        . ci/bin/activate
-        pip install -e ".[docs]"
-        python setup.py build_sphinx
-        cp -r ./build "$CIRCLE_ARTIFACTS"
-  - run:
-      name: Build distribution
-      command: |
-        set -ex
-        . ci/bin/activate
-        pip install docutils
-        pip install Pygments
-        python setup.py --long-description > ../README.rst
-        cat ../README.rst | rst2html.py 1> ../README.html 2> ../log
-        cp ../README.rst "$CIRCLE_ARTIFACTS"
-        cp ../log "$CIRCLE_ARTIFACTS"
-        if [ -s ../log ] ; then
-          cat ../log
-          exit 1
-        fi # rst2html.py alwaysexits with 0, check log size
-        python setup.py bdist_wheel
-        python setup.py sdist
-        mkdir -p "$CIRCLE_ARTIFACTS/dist"
-        cp -r ./dist/* "$CIRCLE_ARTIFACTS/dist"
-  - run:
-      name: Upload to PyPI
-      command: |
-        set -e
-        if [ "$CIRCLE_BRANCH" = "master" ]; then
+          yarn run lint
+    - run:
+        name: Check for JS Formatting Diffs
+        command: |
+          git diff --name-status
+          git diff-files --quiet || (echo 'The files above have not been formatted!' && (exit 1))
+    - run:
+        name: Browserify
+        command: |
+             pushd $YARN_STATIC_DIR
+             yarn run bundle
+    - run:
+        name: JS tests
+        command: |
+             pushd $YARN_STATIC_DIR
+             yarn test
+    - run:
+       name: Create and activate virtualenv
+       command: |
+         virtualenv ci
+         . ci/bin/activate
+         pip install six lxml flake8 tox pytest black .[test]
+         pip install --editable .
+    # Save dependency cache
+    - save_cache:
+        key: v1-dep-{{ .Branch }}-{{ epoch }}
+        paths:
+        - ~/ci
+    - run:
+        name: Run Flake8
+        command: |
           . ci/bin/activate
-          pip install twine
-          export TWINE_USERNAME='__token__'
-          export TWINE_PASSWORD=$PYPI_TOKEN
-          twine upload --skip-existing dist/*
-        fi
-  - store_test_results:
-      path: test-results
-  # Save artifacts. This is silly but wildcards aren't supported.
-  - store_artifacts:
-      path: "/tmp/circleci-artifacts/3_6/dist/"
-  - store_artifacts:
-      path: "/tmp/circleci-artifacts/3_6/build/sphinx/"
-  - store_artifacts:
-      path: "/tmp/circleci-artifacts/3_7/dist/"
-  - store_artifacts:
-      path: "/tmp/circleci-artifacts/3_7/build/sphinx/"
-  - store_artifacts:
-      path: "/tmp/circleci-artifacts/3_8/dist/"
-  - store_artifacts:
-      path: "/tmp/circleci-artifacts/3_8/build/sphinx/"
-  - store_artifacts:
-      path: test-results
-  - persist_to_workspace:
-      root: /tmp/circleci-artifacts
-      paths:
-        - ./*/version.txt
-        - ./*/changes.md
-        - ./*/dist/*
-version: 2
+          flake8 notebooker tests
+    - run:
+        name: Run black
+        command: |
+          . ci/bin/activate
+          black --check -l 120 notebooker tests
+          if [ $? -eq 0 ]
+          then
+            echo "Black worked fine."
+          else
+            echo "Black found differences!"; exit $?
+          fi
+    # Test
+    - run:
+       name: Run all tests
+       command: |
+         set -x
+         . ci/bin/activate
+         ls -la /bin | grep mongo
+         which mongod
+         pip install -e .[prometheus,test]
+         python -m ipykernel install --user --name=notebooker_kernel
+         pip install -r ./notebooker/notebook_templates_example/notebook_requirements.txt
+         mkdir test-results
+         py.test -svvvvv --junitxml=test-results/junit.xml
+         # bash <(curl -s https://codecov.io/bash) -c -F python
+    - run:
+        name: Build Sphinx Documentation
+        command: |
+          set -e
+          . ci/bin/activate
+          pip install -e ".[docs]"
+          python setup.py build_sphinx
+          cp -r ./build "$CIRCLE_ARTIFACTS"
+    - run:
+        name: Build distribution
+        command: |
+          set -ex
+          . ci/bin/activate
+          pip install docutils
+          pip install Pygments
+          python setup.py --long-description > ../README.rst
+          cat ../README.rst | rst2html.py 1> ../README.html 2> ../log
+          cp ../README.rst "$CIRCLE_ARTIFACTS"
+          cp ../log "$CIRCLE_ARTIFACTS"
+          if [ -s ../log ] ; then
+            cat ../log
+            exit 1
+          fi # rst2html.py alwaysexits with 0, check log size
+          python setup.py bdist_wheel
+          python setup.py sdist
+          mkdir -p "$CIRCLE_ARTIFACTS/dist"
+          cp -r ./dist/* "$CIRCLE_ARTIFACTS/dist"
+    - run:
+        name: Upload to PyPI
+        command: |
+          set -e
+          if [ "$CIRCLE_BRANCH" = "master" ]; then
+            . ci/bin/activate
+            pip install twine
+            export TWINE_USERNAME='__token__'
+            export TWINE_PASSWORD=$PYPI_TOKEN
+            twine upload --skip-existing dist/*
+          fi
+    - store_test_results:
+        path: test-results
+    # Save artifacts. This is silly but wildcards aren't supported.
+    - store_artifacts:
+        path: "/tmp/circleci-artifacts/3_6/dist/"
+    - store_artifacts:
+        path: "/tmp/circleci-artifacts/3_6/build/sphinx/"
+    - store_artifacts:
+        path: "/tmp/circleci-artifacts/3_7/dist/"
+    - store_artifacts:
+        path: "/tmp/circleci-artifacts/3_7/build/sphinx/"
+    - store_artifacts:
+        path: "/tmp/circleci-artifacts/3_8/dist/"
+    - store_artifacts:
+        path: "/tmp/circleci-artifacts/3_8/build/sphinx/"
+    - store_artifacts:
+        path: test-results
+    - persist_to_workspace:
+        root: /tmp/circleci-artifacts
+        paths:
+          - ./*/version.txt
+          - ./*/changes.md
+          - ./*/dist/*
+version: 2.1
 jobs:
   build_3_6:
     environment:
@@ -203,15 +205,15 @@ jobs:
     docker:
     - image: cimg/python:3.6-node
     steps:
-    - run:
-        name: Upgrade Node.js
-        command: |
-          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
-          export NVM_DIR="$HOME/.nvm"
-          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-          nvm install 18
-          node --version
-    - *default_steps
+      - run:
+          name: Upgrade Node.js
+          command: |
+            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+            nvm install 18
+            node --version
+      - default_build
     <<: *defaults
   build_3_7:
     environment:
@@ -226,7 +228,7 @@ jobs:
     - image: cimg/python:3.7-node
     <<: *defaults
     steps:
-    - *default_steps
+      - default_build
   build_3_8:
     environment:
       CIRCLE_ARTIFACTS: /tmp/circleci-artifacts/3_8
@@ -240,7 +242,7 @@ jobs:
     - image: cimg/python:3.8-node
     <<: *defaults
     steps:
-    - *default_steps
+      - default_build
   publish-github-release:
     docker:
       - image: cibuilds/github:0.13
